# create prompt templates with variables

from langchain_core.prompts import PromptTemplate

#use for local ollama model
from langchain_ollama import OllamaLLM
#parse structured output json. convert llm text output into structured python obj

from langchain_core.output_parsers import PydanticOutputParser

#build chains. pass data through the chain without modification
from langchain_core.runnables import RunnablePassthrough

from models import BlogTitles
from prompt_template import create_template

from config import (
    OLLAMA_BASE_URL,
    OLLAMA_MODEL,
    TEMPERATURE,
    TOP_P,
    TOP_K,
    NUM_TITLES,
    TIMEOUT_SECONDS
)

import json

def initialize_ollama():
    """
    connect to ollma
    """
    print(f"Connecting to Ollama at {OLLAMA_BASE_URL}")
    llm=OllamaLLM(
        base_url=OLLAMA_BASE_URL,
        model=OLLAMA_MODEL,
        temperature=TEMPERATURE,
        top_p=TOP_P,
        top_k=TOP_K,
        
    )
    return llm



# Main generation function
def generate_blog_titles(topic: str) -> dict:
    """
    Generate blog titles for a given topic
    
    Args:
        topic: The blog topic/subject
        
    Returns:
        Dictionary with titles and strategy explanation
    """
    
    print(f"\n✨ Generating blog titles for: '{topic}'")
    print("⏳ This may take 10-20 seconds on first run...\n")
    
    try:
        # Initialize LLM
        llm = initialize_ollama()
        
        # Create prompt
        prompt = create_template()
        
        # Create chain
        chain = prompt | llm
        
        # Generate
        result = chain.invoke({
            "topic": topic,
            "num_titles": NUM_TITLES
        })
        
        # Parse JSON response
        try:
            # Clean up the response
            json_str = result.strip()
            
            # Remove markdown code blocks if present
            if json_str.startswith("```"):
                json_str = json_str.split("```")[1]
                if json_str.startswith("json"):
                    json_str = json_str[4:]
            
            json_str = json_str.strip()
            
            # Parse JSON
            output = json.loads(json_str)
            
            return {
                "success": True,
                "topic": topic,
                "titles": output.get("titles", []),
                "strategy": output.get("summary", ""),
                "model": OLLAMA_MODEL
            }
            
        except json.JSONDecodeError as e:
            # Fallback: extract titles from raw text
            print("⚠️  Could not parse JSON, using text extraction...")
            lines = result.split('\n')
            titles = [line.strip() for line in lines if line.strip() and not line.startswith('{')][:NUM_TITLES]
            
            return {
                "success": True,
                "topic": topic,
                "titles": titles,
                "strategy": "Generated from text output",
                "model": OLLAMA_MODEL
            }
            
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return {
            "success": False,
            "error": str(e),
            "hint": "Make sure: 1) Ollama is running, 2) Model is installed, 3) You have internet for first pull"
        }


# Display results nicely
def display_results(result: dict):
    """Pretty print the results"""
    
    if not result.get("success"):
        print(f"❌ Failed to generate titles")
        print(f"   Error: {result.get('error')}")
        print(f"   Hint: {result.get('hint')}")
        return
    
    print("\n" + "="*60)
    print(f"📝 Blog Titles for: '{result['topic']}'")
    print(f"🤖 Generated by: {result['model']}")
    print("="*60 + "\n")
    
    for i, title in enumerate(result['titles'], 1):
        print(f"  {i}. {title}")
    
    print(f"\n💡 Strategy: {result['strategy']}")
    print("="*60 + "\n")


# Example usage
if __name__ == "__main__":
    
    # Test topics
    topics = [
        "Artificial Intelligence in Banking",
        "Remote Work Best Practices",
        "Sustainable Technology Trends"
    ]
    
    print("🚀 Blog Title Generator with Local Ollama\n")
    
    for topic in topics:
        result = generate_blog_titles(topic)
        display_results(result)
        print()